// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4JL0BQtMnOLS2cfzoT7w9OJp3N3W4Dqs',
    appId: '1:238235610050:web:b2d82a30be5d053045c45b',
    messagingSenderId: '238235610050',
    projectId: 'crud-app-53183',
    authDomain: 'crud-app-53183.firebaseapp.com',
    storageBucket: 'crud-app-53183.appspot.com',
    measurementId: 'G-TB3XCG59CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrUfZMEAkwksLgwYzvXGFZjdUxy2j6JS0',
    appId: '1:238235610050:android:5d83cbce255ca8dc45c45b',
    messagingSenderId: '238235610050',
    projectId: 'crud-app-53183',
    storageBucket: 'crud-app-53183.appspot.com',
  );
}
